import * as THREE from './vendor/three/three.module.js';
const $=id=>document.getElementById(id);
const projects=[
 {title:'Aicestore',type:'Business / digital products',body:'A digital storefront with a product catalog, pricing and stock information, and an order lookup page. An exploration of a clearer shopping experience, from choosing a product to checking an order.',object:'A stack of catalogs marks the entrance to the store. This object does not display order data.',url:'https://aicestore.web.id'},
 {title:'AireshGPT',type:'AI experiment / Telegram',body:'A Telegram bot project by Aicerubyjane. Follow the public link to view its profile and start a conversation on Telegram; this portfolio does not send messages or access user conversations.',object:'Two intersecting rings represent a conversation, not the bot interface.',url:'https://t.me/aireshgpt_bot'},
 {title:'Aicy Photobox',type:'Camera / creative web',body:'A browser-based photo booth for taking pictures, choosing layouts, filters, stickers, and captions, then downloading photo strips. The static demo offers free watermarked downloads; QRIS payments require a backend and are not active in the GitHub Pages demo.',object:'A picture frame marks this project. This portfolio does not request camera access.',url:'https://aicerubyjane.github.io/Photobox-Web/',repo:'https://github.com/aicerubyjane/Photobox-Web'},
 {title:'Camellia Digital',type:'Business / storefront',body:'A digital product selection page with package details, an order summary, and a handoff to WhatsApp. Final pricing and payment are confirmed with an administrator, not processed on this page.',object:'Porcelain petals represent Camellia: simple, warm, and welcoming.',url:'https://camelliashop.aicerubyjane.my.id/'},
 {title:'IDX Chart Rider',type:'Game / interactive experiment',body:'A 2D physics-based racing game with terrain shaped by Indonesian stock charts. Built with Phaser and Matter.js, as documented in its public repository. This is a game, not a financial analysis tool or investment advice.',object:'Brass contours evoke the terrain of the game, not investment performance.',url:'https://aicerubyjane.github.io/IDX-Chart-Rider/',repo:'https://github.com/aicerubyjane/IDX-Chart-Rider'}
];
let selected=0,opener,collectionFocus=0,roomView=0;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{roomView=Number(b.dataset.view);document.querySelectorAll('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});const dialog=$('detail');
function content(i){selected=i;const p=projects[i];$('detail-type').textContent=`0${i+1} / ${p.type}`;$('detail-title').textContent=p.title;$('detail-body').textContent=p.body;$('detail-object').textContent=p.object;$('visit-project').href=p.url;$('project-source').hidden=!p.repo;$('project-source').href=p.repo||p.url;}
function open(i,from){opener=from||$('list-toggle');content(i);dialog.showModal();document.body.style.overflow='hidden';$('close').focus();setTimeout(()=>$('close').focus(),50);}
$('close').onclick=()=>dialog.close();$('next').onclick=()=>content((selected+1)%5);
dialog.addEventListener('close',()=>{document.body.style.overflow='';(opener?.getClientRects().length?opener:$('list-toggle')).focus({preventScroll:true});});
dialog.addEventListener('keydown',e=>{if(e.key==='Tab'){if(e.shiftKey&&document.activeElement===$('close')){e.preventDefault();$('next').focus();}else if(!e.shiftKey&&document.activeElement===$('next')){e.preventDefault();$('close').focus();}}});
projects.forEach((p,i)=>{const b=document.createElement('button');b.innerHTML=`<span>0${i+1}</span>${p.title}<i aria-hidden="true">↗</i>`;b.onclick=()=>open(i,b);b.onpointerenter=b.onfocus=()=>{collectionFocus=i;};$('accessible-projects').append(b);});
$('list-toggle').onclick=()=>{window.scrollTo({top:$('project-list').offsetTop,behavior:'instant'});$('accessible-projects').firstElementChild.focus({preventScroll:true});};$('back-room').onclick=()=>window.scrollTo({top:0,behavior:'instant'});
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let motionOff=reduced;
function motion(){ $('motion').textContent=motionOff?'Enable motion':'Pause motion';$('motion').setAttribute('aria-pressed',String(motionOff)); }motion();$('motion').onclick=()=>{motionOff=!motionOff;motion();};matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{motionOff=e.matches;motion();});
// Sound is synthesized locally, starts only after an explicit gesture.
let audio;let soundOn=false;
$('ambient').onclick=async()=>{try{if(!audio){audio=new AudioContext();const gain=audio.createGain();gain.gain.value=.025;gain.connect(audio.destination);[130.81,196,261.63].forEach(f=>{const o=audio.createOscillator();o.type='sine';o.frequency.value=f;o.connect(gain);o.start();});}soundOn=!soundOn;await audio[soundOn?'resume':'suspend']();$('ambient').textContent=soundOn?'Room sound: on ♫':'Room sound: off ♫';$('ambient').setAttribute('aria-pressed',String(soundOn));}catch{$('ambient').textContent='Audio unavailable';}};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&audio){audio.suspend();soundOn=false;$('ambient').textContent='Room sound: off ♫';$('ambient').setAttribute('aria-pressed','false');}});
window.sceneState={rendered:false};
function fallback(){document.body.classList.add('fallback');$('list-title').textContent='Projects by Aicerubyjane.';window.sceneState.fallback=true;}
try { await build(); } catch(e){console.warn('The 3D room is unavailable; you can still use the project list.',e.message);fallback();}
async function build(){
 const canvas=$('world');const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.96;renderer.outputColorSpace=THREE.SRGBColorSpace;
 const scene=new THREE.Scene();scene.background=new THREE.Color('#eee8df');scene.fog=new THREE.Fog('#eee8df',24,48);const camera=new THREE.PerspectiveCamera(39,innerWidth/innerHeight,.1,80);
 const mat=(color,roughness=.7,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});
 const plaster=mat('#e7e0d3'),stone=mat('#c9b9a1'),wood=mat('#78604b'),ruby=mat('#79414b',.4),lilac=mat('#aaa0b5',.45),paper=mat('#e4ddce'),brass=mat('#ad8b57',.3,.7),dark=mat('#49433e');
 const grain=document.createElement('canvas');grain.width=grain.height=256;const ctx=grain.getContext('2d');const image=ctx.createImageData(256,256);let seed=82;for(let i=0;i<image.data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;const v=195+(seed%50);image.data[i]=image.data[i+1]=image.data[i+2]=v;image.data[i+3]=255;}ctx.putImageData(image,0,0);const texture=new THREE.CanvasTexture(grain);texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(6,6);plaster.map=texture;stone.bumpMap=texture;stone.bumpScale=.018;
 function mesh(geo,material,parent=scene,x=0,y=0,z=0){const m=new THREE.Mesh(geo,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 function box(w,h,d,m,p=scene,x=0,y=0,z=0){return mesh(new THREE.BoxGeometry(w,h,d),m,p,x,y,z);}
 function cyl(r,h,m,p=scene,x=0,y=0,z=0){return mesh(new THREE.CylinderGeometry(r,r,h,64),m,p,x,y,z);}
 box(60,.18,50,plaster,scene,0,-.12,0);box(28,11,.25,plaster,scene,0,5.4,-5.5);
 // Tall daylight openings, deep reveals and slender mullions, not a dollhouse.
 const daylight=new THREE.MeshBasicMaterial({color:'#fff9e9'});
 for(let i=0;i<3;i++){const x=-9+i*3.1;box(2.4,6.8,.09,daylight,scene,x,4.3,-5.32);box(.10,6.8,.25,wood,scene,x,4.3,-5.18);box(2.5,.1,.26,wood,scene,x,3.7,-5.18);box(2.65,.17,.65,stone,scene,x,.86,-5.03);}
 // A softly lit gallery alcove and one continuous, monolithic display.
 box(12.4,.28,3.3,stone,scene,0,1.8,0);box(.8,1.65,2.7,stone,scene,-4.4,.86,0);box(.8,1.65,2.7,stone,scene,4.4,.86,0);
 for(let i=0;i<12;i++)box(12.25,.008,.014,wood,scene,0,1.95,-1.4+i*.25);
 // Fine floor joints establish scale.
 for(let i=-12;i<13;i+=2)box(.012,.006,28,mat('#d5cbbb'),scene,i,-.025,0);
 // Warm linear sunlight lying across the floor; translucent physical-light study.
 const sunpatch=new THREE.MeshBasicMaterial({color:'#fff5d8',transparent:true,opacity:.22,depthWrite:false});
 for(let i=0;i<3;i++){const p=box(2.05,.009,10,sunpatch,scene,-5.5+i*3,.005,1.6);p.rotation.y=-.45;p.castShadow=false;}
 const ambient=new THREE.HemisphereLight('#fff9ee','#b0a08c',1.65);scene.add(ambient);const sun=new THREE.DirectionalLight('#fff1d3',3.4);sun.position.set(-7,12,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-12,right:12,top:10,bottom:-10,near:1,far:35});sun.shadow.bias=-.00035;sun.shadow.normalBias=.035;sun.shadow.radius=4;scene.add(sun);scene.add(new THREE.AmbientLight('#e4deef',.35));
 // Procedural oak grain; no downloaded texture or unlicensed asset.
 const oak=document.createElement('canvas');oak.width=128;oak.height=512;const oc=oak.getContext('2d');oc.fillStyle='#a08869';oc.fillRect(0,0,128,512);for(let i=0;i<180;i++){oc.strokeStyle=`rgba(51,30,15,${.03+(i%7)*.012})`;oc.beginPath();for(let y=0;y<513;y+=8){const x=(i*.87+Math.sin(y*.012+i)*2)%128;y?oc.lineTo(x,y):oc.moveTo(x,y);}oc.stroke();}const ot=new THREE.CanvasTexture(oak);ot.wrapS=ot.wrapT=THREE.RepeatWrapping;wood.map=ot;wood.bumpMap=ot;wood.bumpScale=.025;plaster.bumpMap=texture;plaster.bumpScale=.012;
 // Soft contact occlusion baked procedurally into alpha gradients.
 const contact=document.createElement('canvas');contact.width=contact.height=128;const cc=contact.getContext('2d');const cg=cc.createRadialGradient(64,64,3,64,64,63);cg.addColorStop(0,'rgba(55,38,24,.38)');cg.addColorStop(.5,'rgba(55,38,24,.16)');cg.addColorStop(1,'rgba(55,38,24,0)');cc.fillStyle=cg;cc.fillRect(0,0,128,128);const ct=new THREE.CanvasTexture(contact);
 function softContact(x,y,z,w,d){const m=mesh(new THREE.PlaneGeometry(w,d),new THREE.MeshBasicMaterial({map:ct,transparent:true,depthWrite:false}),scene,x,y,z);m.rotation.x=-Math.PI/2;m.castShadow=false;}
 [-4.4,4.4].forEach(x=>softContact(x,-.018,0,2.5,4));[-4.45,-2.13,.25,2.58,4.85].forEach(x=>softContact(x,1.955,0,2.1,1.8));
 // Botanical gobo on the wall: layered, blurred leaf silhouettes.
 const foliage=document.createElement('canvas');foliage.width=foliage.height=512;const fc=foliage.getContext('2d');fc.filter='blur(5px)';for(let i=0;i<95;i++){const x=256+Math.sin(i*2.4)*210,y=256+Math.cos(i*1.7)*230;fc.fillStyle='rgba(61,54,38,.13)';fc.beginPath();fc.ellipse(x,y,12+i%19,5+i%9,i*.6,0,Math.PI*2);fc.fill();}const ft=new THREE.CanvasTexture(foliage);const fm=new THREE.MeshBasicMaterial({map:ft,transparent:true,depthWrite:false});const wallLeaves=mesh(new THREE.PlaneGeometry(14,9),fm,scene,-3,4.5,-5.35);wallLeaves.castShadow=false;const floorLeaves=mesh(new THREE.PlaneGeometry(12,9),fm,scene,-4,-.012,3);floorLeaves.rotation.x=-Math.PI/2;floorLeaves.rotation.z=-.4;floorLeaves.castShadow=false;
 const objects=[],anchors=[],labels=[];
 function project(i,x,z=0){const g=new THREE.Group();g.position.set(x,1.96,z);scene.add(g);g.userData.project=i;objects.push(g);return g;}
 const catalog=project(0,-4.45,.12);catalog.rotation.y=.10;for(let i=0;i<3;i++){const b=box(1.55,.16,1.1,i===2?ruby:paper,catalog,0,.13+i*.19,0);b.rotation.y=i*.065;box(1.25,.024,.015,brass,catalog,0,.59,.56);}box(.055,.08,1.11,brass,catalog,-.48,.61,0);
 const ai=project(1,-2.13,-.13);cyl(.74,.12,stone,ai,0,.06,0);for(let i=0;i<2;i++){const ring=mesh(new THREE.TorusGeometry(.55,.105,24,80),i?lilac:brass,ai,i*.28-.14,.73,0);ring.rotation.y=i?-.55:.55;}
 const photo=project(2,.25,-.05);box(1.2,.1,.85,dark,photo,0,.05,0);for(const x of [-.55,.55])box(.10,1.7,.15,ruby,photo,x,.9,0);for(const y of [.1,1.7])box(1.2,.1,.15,ruby,photo,0,y,0);const inner=box(.94,1.4,.025,paper,photo,0,.9,.015);const art=mat('#b6a7ba');mesh(new THREE.CircleGeometry(.33,64),art,photo,0,1.09,.036);box(.92,.37,.018,stone,photo,0,.39,.04);
 const camellia=project(3,2.58,0);cyl(.72,.12,stone,camellia,0,.06,0);for(let i=0;i<5;i++){const petal=mesh(new THREE.SphereGeometry(1,32,20),i%2?paper:lilac,camellia,Math.cos(i*Math.PI*2/5)*.3,.5,Math.sin(i*Math.PI*2/5)*.3);petal.scale.set(.24,.42,.14);petal.rotation.z=Math.cos(i)*.4;}cyl(.13,.55,brass,camellia,0,.33,0);
 const idx=project(4,4.85,.03);cyl(.73,.11,stone,idx,0,.05,0);for(let i=0;i<5;i++){const fin=box(.12,.6+Math.sin(i*1.7)*.22,.72,i%2?lilac:brass,idx,(i-2)*.23,.43,0);fin.rotation.y=-.25;}
 // One sculptural branch supplies scale and warmth without a toy-room inventory.
 const vase=scene;mesh(new THREE.SphereGeometry(.43,40,28),mat('#a29e8b'),vase,7,.52,-2.9);cyl(.20,.45,mat('#a29e8b'),vase,7,.85,-2.9);
 for(let i=0;i<3;i++){const stem=new THREE.CatmullRomCurve3([new THREE.Vector3(7,1,-2.9),new THREE.Vector3(6.9+i*.2,1.9,-2.9),new THREE.Vector3(6.3+i*.5,2.8-i*.2,-2.8)]);mesh(new THREE.TubeGeometry(stem,15,.015,6,false),wood);for(let j=0;j<4;j++){const leaf=mesh(new THREE.SphereGeometry(1,16,8),mat('#8e9276'),scene,6.5+i*.36+j*.05,1.6+j*.28,-2.85);leaf.scale.set(.2,.05,.09);leaf.rotation.z=.4+i;}}
 objects.forEach((g,i)=>{anchors.push(new THREE.Vector3(g.position.x,g.position.y+(i===2?2.02:1.6),g.position.z));const b=document.createElement('button');b.className='hotspot';b.setAttribute('aria-label','Open '+projects[i].title);b.innerHTML=`<span>0${i+1}</span>${projects[i].title}`;b.onclick=()=>open(i,b);b.onpointerenter=()=>hover=i;b.onpointerleave=()=>hover=-1;$('labels').append(b);labels.push(b);g.traverse(m=>{if(m.isMesh)m.userData.project=i;});});
 const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let px=0,py=0,sx=0,sy=0,hover=-1,down=null;
 function pick(e){pointer.set(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2);raycaster.setFromCamera(pointer,camera);return raycaster.intersectObjects(objects,true)[0]?.object.userData.project;}
 canvas.addEventListener('pointermove',e=>{px=e.clientX/innerWidth-.5;py=e.clientY/innerHeight-.5;hover=pick(e)??-1;canvas.style.cursor=hover>=0?'pointer':'default';});canvas.addEventListener('pointerleave',()=>{px=py=0;hover=-1;});canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};});canvas.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<12){const i=pick(e);if(i!==undefined)open(i,labels[i]);}down=null;});
 const chapters=[['01 / THE ROOM','Step inside. Look closer.','Five projects by Aicerubyjane, in one room. Scroll to explore.'],['02 / SYSTEMS','From ideas to products.','Aicestore and AireshGPT. Digital business meets AI experiments.'],['03 / EXPLORATION','Room to experiment.','Aicy Photobox, Camellia Digital, and IDX Chart Rider. Keep scrolling to meet Aicerubyjane.']];
 renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;
 let progress=0,lastChapter=-1,frames=0,lastTime=performance.now();const target=new THREE.Vector3();
 function maxScroll(){return $('journey').offsetHeight-innerHeight;}
 document.querySelectorAll('[data-stop]').forEach(b=>b.onclick=()=>window.scrollTo({top:maxScroll()*Number(b.dataset.stop)/2,behavior:motionOff?'instant':'smooth'}));
 function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);$('hint').textContent=innerWidth<650?'SWIPE TO EXPLORE · TAP AN OBJECT':'MOVE YOUR POINTER · SELECT AN OBJECT';}resize();addEventListener('resize',resize);
 canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();fallback();});
 function render(){requestAnimationFrame(render);if(document.hidden||document.body.classList.contains('fallback'))return;const p=Math.max(0,Math.min(1,scrollY/maxScroll()));const now=performance.now(),alpha=1-Math.exp(-Math.min(1,(now-lastTime)/1000)*8);lastTime=now;progress=motionOff?Math.round(p*2)/2:THREE.MathUtils.lerp(progress,p,alpha);sx=THREE.MathUtils.lerp(sx,px,alpha*.5);sy=THREE.MathUtils.lerp(sy,py,alpha*.5);const mobile=innerWidth<650;const poses=mobile?[[10,10,19,0,1,0],[-4,6.6,12,-3.1,2,0],[5,6.7,12,2.8,2,0]]:[[10.5,8.3,14.5,0,1.2,0],[-5.8,5.3,9,-3.2,2,0],[5.8,5.3,9,2.4,2,0]];let k=Math.min(1,Math.floor(progress*2)),t=progress*2-k;t=t*t*(3-2*t);const a=poses[k],b=poses[k+1];camera.position.set(THREE.MathUtils.lerp(a[0],b[0],t)+(motionOff?0:sx*.35),THREE.MathUtils.lerp(a[1],b[1],t)+(motionOff?0:sy*.16),THREE.MathUtils.lerp(a[2],b[2],t));target.set(THREE.MathUtils.lerp(a[3],b[3],t),THREE.MathUtils.lerp(a[4],b[4],t),0);const beyond=Math.max(0,Math.min(1,(scrollY-( $('journey').offsetHeight-innerHeight))/innerHeight));
 const aboutTop=$('about').offsetTop,contactTop=$('contact').offsetTop;
 let roomChapter='collection',pose;
 if(scrollY<aboutTop-innerHeight*.35){const x=objects[collectionFocus].position.x;pose=[x+2.8,5.2,8,x,2,0];}
 else if(scrollY<contactTop-innerHeight*.35){roomChapter='about';pose=roomView?[6.8,4.5,8,1,2,0]:[-8,5.5,9,-4,2,-2];}
 else{roomChapter='contact';pose=[8,4.2,10,4,2,-1];}
 if(beyond>0){const desired=new THREE.Vector3(pose[0],pose[1],pose[2]);if(!window.roomCamera)window.roomCamera=desired.clone();window.roomCamera.lerp(desired,motionOff?1:alpha);camera.position.lerp(window.roomCamera,beyond);target.lerp(new THREE.Vector3(pose[3],pose[4],pose[5]),beyond);}
 document.body.classList.toggle('in-room-notes',beyond>.95);camera.lookAt(target);camera.updateMatrixWorld();
 const chapter=Math.round(progress*2);if(chapter!==lastChapter){lastChapter=chapter;$('chapter-index').textContent=chapters[chapter][0];$('chapter-title').textContent=chapters[chapter][1];$('chapter-copy').textContent=chapters[chapter][2];document.querySelectorAll('[data-stop]').forEach(b=>b.setAttribute('aria-current',String(Number(b.dataset.stop)===chapter)));}
 objects.forEach((g,i)=>{const y=1.96;g.position.y=motionOff?1.96:THREE.MathUtils.lerp(g.position.y,y,.12);labels[i].classList.toggle('active',i===hover);});
 const projected=[];anchors.forEach((v,i)=>{const s=v.clone().project(camera);const x=(s.x*.5+.5)*innerWidth,y=(-s.y*.5+.5)*innerHeight;let visible=s.z<1&&x>55&&x<innerWidth-55&&y>115&&y<innerHeight-245;if(mobile){visible=visible&&(chapter===0?(i===1||i===3):chapter===1?i<2:i>=2);}if(mobile&&chapter===1&&i<2)visible=true;const labelX=Math.max(85,Math.min(innerWidth-85,x));labels[i].style.left=labelX+'px';labels[i].style.top=y+'px';labels[i].style.display=visible?'flex':'none';projected.push({i,x,y,visible});});
 $('progress').style.width=progress*100+'%';renderer.render(scene,camera);$('loading').hidden=true;window.sceneState={rendered:true,frames:++frames,progress,roomChapter,beyond,collectionFocus,roomView,camera:camera.position.toArray(),hover,motionOff,projected,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,objectCenters:objects.map(g=>{const v=g.position.clone();v.y+=.45;v.project(camera);return {x:(v.x*.5+.5)*innerWidth,y:(-.5*v.y+.5)*innerHeight};})};}
 render();
}
