import * as THREE from './vendor/three/three.module.js';
const $=s=>document.querySelector(s), reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const projects=[
['Aicestore','Commerce','A storefront for digital products, connecting an interest in business with building for the web.','Public Aicestore website capture. This is a still preview, not a live checkout.','https://aicestore.web.id'],
['AireshGPT','AI & automation','A Telegram AI bot, explored here as a conversational entry point to digital tools.','Actual public Telegram landing capture. No private conversation or bot session was opened.','https://t.me/aireshgpt_bot'],
['Aicy Photobox','Creative tools','A browser photo booth for capturing, decorating, and downloading photo strips, as described in the public repository.','Landing page rendered locally from the public Photobox-Web repository with external requests blocked. The public demo timed out. No camera was accessed.','https://aicerubyjane.github.io/Photobox-Web/','https://github.com/aicerubyjane/Photobox-Web'],
['Camellia Digital','Digital business','A digital shop project, reflecting an interest in presenting products and building an online business.','Actual public Camellia Digital website capture. This still preview does not place an order.','https://camelliashop.aicerubyjane.my.id/'],
['IDX Chart Rider','Browser play','A browser game published through its public GitHub repository and demo. It is not a financial analysis or investment tool.','Actual game welcome screen rendered locally from the public IDX-Chart-Rider repository with external requests blocked. The public demo timed out. This is not live gameplay.','https://aicerubyjane.github.io/IDX-Chart-Rider/','https://github.com/aicerubyjane/IDX-Chart-Rider']];
let lastFocus;const dialog=$('#project-dialog');document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{lastFocus=b;const p=projects[+b.dataset.project];$('#dialog-category').textContent=p[1];$('#dialog-title').textContent=p[0];$('#dialog-body').textContent=p[2];$('#dialog-preview').textContent=p[3];$('#dialog-image').src='assets/'+['aicestore','airesh','photobox','camellia','idx'][+b.dataset.project]+'.png';$('#dialog-image').alt=p[0]+' — captured project preview';$('#dialog-links').replaceChildren(...p.slice(4).map((url,i)=>{const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.textContent=i?'View source ↗':'Open project ↗';return a}));dialog.showModal()});$('.close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>lastFocus?.focus());dialog.addEventListener('click',e=>{if(e.target===dialog&&e.clientX<dialog.getBoundingClientRect().left)dialog.close()});
dialog.addEventListener('keydown',e=>{if(e.key==='Tab'){const nodes=[...dialog.querySelectorAll('button,a[href]')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
$('#view').onclick=()=>{if(!state.webgl){$('#status').textContent='Spatial view requires WebGL. All projects remain available below.';return;}const on=document.body.classList.toggle('list-mode');$('#view').setAttribute('aria-pressed',on);$('#view').textContent=on?'Spatial view':'List view';};
const state={progress:0,camera:[],frames:0,actions:{},webgl:false,reduced};window.previewState=state;
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('#world'),antialias:true,alpha:false});}catch(e){document.body.classList.add('list-mode');$('#status').textContent='3D unavailable. All projects and links remain available in list view.';}
const acts={};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const i=+b.dataset.action;state.actions[i]=(state.actions[i]||0)+1;acts[i]=!acts[i];const messages={1:'Storefront display turned.',2:'Computer turned. Public Telegram landing only.',3:'Computer turned. Source-rendered photo booth preview.',4:'Computer turned. Public shop capture.',5:'Computer turned. Source-rendered game welcome screen.',6:'Development, business, and AI connected.',7:'A local signal sent through the scene. No message transmitted.'};$('#status').textContent=messages[i];clearTimeout(window.statusTimer);window.statusTimer=setTimeout(()=>$('#status').textContent='',4500)});
if(renderer){
state.webgl=true;renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor(0xeaf0f5);const scene=new THREE.Scene();scene.fog=new THREE.Fog(0xeaf0f5,35,115);const camera=new THREE.PerspectiveCamera(38,1,.1,200);
scene.add(new THREE.HemisphereLight(0xf5f9ff,0x8193a8,2.0));const fill=new THREE.DirectionalLight(0xdbeaff,1.1);fill.position.set(12,8,6);scene.add(fill);const sun=new THREE.DirectionalLight(0xffffff,2.6);sun.position.set(-8,18,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-20,right:20,top:20,bottom:-20,far:70});sun.shadow.bias=-.0004;scene.add(sun);scene.add(sun.target);
const mat=(color,metalness=0,roughness=.55)=>new THREE.MeshStandardMaterial({color,metalness,roughness});const cream=mat(0xe5edf4,.12,.42),ruby=mat(0x6689ae,.35,.32),lilac=mat(0xb5c9df,.25,.4),dark=mat(0x202b39,.35,.35),gold=mat(0x9db3c9,.48,.36),paper=mat(0xf3f7fc,.08,.4);
function mesh(g,m,parent,x=0,y=0,z=0){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}function box(parent,w,h,d,m,x=0,y=0,z=0){const radius=Math.min(.075,h*.22,d*.22),s=new THREE.Shape(),a=-w/2,b=-h/2;s.moveTo(a+radius,b);s.lineTo(a+w-radius,b);s.quadraticCurveTo(a+w,b,a+w,b+radius);s.lineTo(a+w,b+h-radius);s.quadraticCurveTo(a+w,b+h,a+w-radius,b+h);s.lineTo(a+radius,b+h);s.quadraticCurveTo(a,b+h,a,b+h-radius);s.lineTo(a,b+radius);s.quadraticCurveTo(a,b,a+radius,b);const geo=new THREE.ExtrudeGeometry(s,{depth:d-radius*2,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:radius,bevelThickness:radius,curveSegments:5});geo.translate(0,0,-d/2+radius);return mesh(geo,m,parent,x,y,z)}function sphere(parent,r,m,x=0,y=0,z=0){return mesh(new THREE.SphereGeometry(r,36,24),m,parent,x,y,z)}function ring(parent,r,t,m,x=0,y=0,z=0){return mesh(new THREE.TorusGeometry(r,t,16,100),m,parent,x,y,z)}
const floor=mesh(new THREE.PlaneGeometry(200,220),mat(0xe5edf4,0,.8),scene,0,-.65,-45);floor.rotation.x=-Math.PI/2;
const groups=[],moving=[];
function label(text,w=1024,h=256){const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle='#e5edf4';ctx.fillRect(0,0,w,h);ctx.fillStyle='#526a80';ctx.font='44px sans-serif';ctx.textAlign='center';ctx.fillText(text,w/2,h/2+15);return new THREE.CanvasTexture(c)}
for(let i=1;i<=7;i++){let g=new THREE.Group();g.position.set(3,0,-16*(i-1));scene.add(g);groups[i]=g;const base=mesh(new THREE.CylinderGeometry(4,4.15,.28,100),cream,g,0,-.45);const rim=ring(g,3.98,.025,gold,0,-.28);rim.rotation.x=-Math.PI/2;const arc=mesh(new THREE.TorusGeometry(4.65,.065,14,120,Math.PI),gold,g,0,1,-1.7);}
// Broad, soft contact occlusion under each pedestal, independent of directional shadow resolution.
const shadowCanvas=document.createElement('canvas');shadowCanvas.width=256;shadowCanvas.height=256;const sc=shadowCanvas.getContext('2d'),gradient=sc.createRadialGradient(128,128,30,128,128,126);gradient.addColorStop(0,'rgba(42,62,87,.23)');gradient.addColorStop(.6,'rgba(42,62,87,.12)');gradient.addColorStop(1,'rgba(42,62,87,0)');sc.fillStyle=gradient;sc.fillRect(0,0,256,256);const shadowTexture=new THREE.CanvasTexture(shadowCanvas);for(let i=1;i<=7;i++){const o=mesh(new THREE.PlaneGeometry(12,12),new THREE.MeshBasicMaterial({map:shadowTexture,transparent:true,depthWrite:false}),groups[i],0,-.635);o.rotation.x=-Math.PI/2;o.castShadow=false;o.receiveShadow=false;}
const assets=['aicestore','airesh','photobox','camellia','idx'];
for(let i=1;i<=5;i++){
 const computer=new THREE.Group();groups[i].add(computer);moving[i]=computer;
 const silver=mat(0xbfcddd,.52,.32);
 box(computer,6.15,4.0,.22,silver,0,2.55,0);
 box(computer,5.97,3.82,.06,dark,0,2.55,.135);
 const tex=new THREE.TextureLoader().load('assets/'+assets[i-1]+'.png');tex.colorSpace=THREE.SRGBColorSpace;
 mesh(new THREE.PlaneGeometry(5.76,3.6),new THREE.MeshBasicMaterial({map:tex,toneMapped:false}),computer,0,2.58,.173);
 box(computer,.48,1.0,.24,silver,0,.42,-.08);box(computer,1.9,.10,1.0,silver,0,-.05,.18);
 box(computer,3,.11,1.05,silver,0,-.13,1.8);
 for(let r=0;r<4;r++)for(let c=0;c<12;c++)box(computer,.2,.025,.15,paper,-1.3+c*.235,-.06,1.47+r*.2);
 const mouse=sphere(computer,.25,silver,2,-.06,1.8);mouse.scale.set(.7,.3,1.2);
}
const nodes=[];for(let k=0;k<3;k++){const a=k*Math.PI*2/3;const p=new THREE.Vector3(Math.cos(a)*2,2+Math.sin(a)*2,0);const node=sphere(groups[6],.65,[ruby,lilac,gold][k],p.x,p.y,p.z);nodes.push(node);const r=ring(groups[6],1.2,.025,gold,p.x,p.y,p.z);r.rotation.y=.5}const connection=new THREE.Line(new THREE.BufferGeometry().setFromPoints([...nodes.map(n=>n.position),nodes[0].position]),new THREE.LineBasicMaterial({color:0x6b8bab}));groups[6].add(connection);connection.visible=false;
const signals=[];for(let k=0;k<5;k++){const r=ring(groups[7],.8+k*.5,.055,k%2?lilac:gold,0,2,-k*.45);signals.push(r)}sphere(groups[7],.45,ruby,0,2,.2);
// Keep the foreground clear; the rear architectural arc anchors each station.
let drag=0,down=false,lastX=0;const canvas=$('#world');canvas.addEventListener('pointerdown',e=>{down=true;lastX=e.clientX;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(down){drag=Math.max(-2,Math.min(2,drag+(e.clientX-lastX)*.008));lastX=e.clientX}});canvas.addEventListener('pointerup',()=>down=false);
const ray=new THREE.Raycaster();canvas.addEventListener('click',e=>{if(Math.abs(drag)>.3)return;ray.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const i=state.active;if(i>0&&ray.intersectObjects(groups[i].children,true).length)document.querySelector(`[data-action="${i}"]`)?.click()});
function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
const sections=[...document.querySelectorAll('main section')],target=new THREE.Vector3(),look=new THREE.Vector3();let current=0,previousActive=-1,arrival=1,clock=new THREE.Clock();
function frame(){requestAnimationFrame(frame);const t=clock.getElapsedTime(),mobile=innerWidth<701;let p=0;for(let i=0;i<sections.length-1;i++){if(scrollY>=sections[i].offsetTop){p=i+Math.min(1,(scrollY-sections[i].offsetTop)/(sections[i+1].offsetTop-sections[i].offsetTop))}}p=Math.min(7,p);current=reduced?p:THREE.MathUtils.lerp(current,p,.085);state.progress=current;
const active=Math.max(0,Math.min(7,Math.floor(p+.42)));state.active=active;document.body.dataset.active=active;if(active!==previousActive){arrival=0;previousActive=active;$('#status').textContent='';}arrival=reduced?1:THREE.MathUtils.lerp(arrival,1,.09);state.station=Math.max(1,active);
sections.forEach((section,i)=>{section.classList.toggle('current',i===active);section.inert=!document.body.classList.contains('list-mode')&&i!==active;});
const z=-16*(Math.max(1,active)-1);const phase=reduced?0:Math.sin((p-active)*Math.PI)*.6;
target.set(mobile?3:7, mobile?4.5:5,z+(mobile?(innerWidth<350?33:30):14)+phase);look.set(mobile?3:-.1,mobile?-2.0:1.7,z);target.x+=drag*.3;camera.position.copy(target);camera.lookAt(look);sun.position.set(-8,18,z+16);sun.target.position.set(3,0,z);
for(let i=1;i<=7;i++){groups[i].visible=i===Math.max(1,active);groups[i].position.y=-.12*(1-arrival);}fill.position.set(12,8,z+6);
for(let i=1;i<=5;i++)moving[i].rotation.y=THREE.MathUtils.lerp(moving[i].rotation.y,acts[i]?-.28:.04,reduced?1:.08);connection.visible=!!acts[6];groups[6].rotation.y=acts[6]&&!reduced?Math.sin(t*.4)*.5:0;signals.forEach((r,k)=>{r.scale.setScalar(acts[7]?1+(reduced?.15:Math.sin(t*2-k*.6)*.12):1);});
document.querySelectorAll('.journey a').forEach((a,i)=>a.classList.toggle('active',i===active));renderer.render(scene,camera);state.frames++;state.camera=camera.position.toArray();}frame();
}
